/*
 * MapEditor.java
 *
 * Created on 7 de octubre de 2008, 10:22 PM
 */

package psychotileeditor;

import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author  xyon
 */
public class MapEditor extends javax.swing.JFrame implements MouseMotionListener, MouseListener{
    private Mapa map;
    
    /** Creates new form MapEditor */
    public MapEditor() {
        initComponents();
        this.addMouseMotionListener(this);
    }
    
    public MapEditor(Mapa m){
        this();
        map = m;
        this.setVisible(true);
    }
    
    public MapEditor(String rutaMapa) {
        this(new Mapa(rutaMapa, 26, 16));
    }
        
    public Mapa getMapa(){
        return map;
    }
    
    
    @Override
    public void paint(Graphics g){
//        super.paint(g);
        g.drawImage(map.getFondo(), 0, 20, this);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PsychoStrain Map");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(768, 480));
        setName("MapWindow"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mouseDragged(MouseEvent e) {
    }
    public void mouseMoved(MouseEvent e) {
        this.repaint();
    }
    public void mouseClicked(MouseEvent e) {
    }
    public void mousePressed(MouseEvent e) {
    }
    public void mouseReleased(MouseEvent e) {
    }
    public void mouseEntered(MouseEvent e) {
    }
    public void mouseExited(MouseEvent e) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}