
//optPanel.java

package PsychoMenu;
import PsychoGame.Engine;

//  PsySoft Team 2008
import java.awt.Font;
//       (Manuel Espinoza, Alberto Zorrilla, Guillermo Leon y Arquimides Diaz)
import java.io.File;

public class optPanel extends javax.swing.JFrame {
  
  private boolean listenClicked = false;
  
    public optPanel() {
     initComponents();
    try {
        Engine.staticOpt.loadConfig(); //cargar la configuracion del archivo de texto
        setFields(); //con la informacion cargada, llenar los text fields
        setCrazy();
      } catch (NumberFormatException e) { //si el hashmap esta vacio (o el archivo no existia) cargar defaults
        Engine.staticOpt.loadDefaults(); 
        setFields();
        setCrazy();
      } catch (NullPointerException e) { //si el hashmap esta vacio (o el archivo no existia) cargar defaults
        Engine.staticOpt.loadDefaults(); //NumberFormatException
        setFields();
        setCrazy();
      }             
    }
    
    public void setCrazy(){
    try {
      Font crazy = Font.createFont(Font.TRUETYPE_FONT, new File("fonts/byte.ttf"));
      crazy = crazy.deriveFont(14f);
      jLabel2.setFont(crazy);
      jLabel1.setFont(crazy);
      jLabel3.setFont(crazy);
      jLabel4.setFont(crazy);
      jLabel5.setFont(crazy);
      jLabel6.setFont(crazy);
      jLabel7.setFont(crazy);
      jLabel8.setFont(crazy);
      jLabel9.setFont(crazy);
      jButton2.setFont(crazy);
      jButton1.setFont(crazy);
      jButton3.setFont(crazy);
      jButton4.setFont(crazy);
      jButton5.setFont(crazy);
      jButton6.setFont(crazy);
      jButton7.setFont(crazy);
      jButton8.setFont(crazy);
      jButton9.setFont(crazy);
      defaultsBtn.setFont(crazy);
      exitBtn.setFont(crazy);
    } catch (Exception ex) {}
  }
    
  @SuppressWarnings("static-access")
    public void setFields(){
      java.awt.event.KeyEvent evt = null;
      salto.setText(evt.getKeyText(Engine.staticOpt.getSalto()));
      derecha.setText(evt.getKeyText(Engine.staticOpt.getDerecha()));
      izquierda.setText(evt.getKeyText(Engine.staticOpt.getIzquierda()));
      abajo.setText(evt.getKeyText(Engine.staticOpt.getAbajo()));
      disparo.setText("Boton "+Engine.staticOpt.getDisparo());
      cmd.setText(evt.getKeyText(Engine.staticOpt.getCmd()));    
      pausa.setText(evt.getKeyText(Engine.staticOpt.getPausa()));
      chgGun.setText(evt.getKeyText(Engine.staticOpt.getGuns()));              
      up.setText(evt.getKeyText(Engine.staticOpt.getUp())); 
    }
    
   /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    pausa = new javax.swing.JTextField();
    salto = new javax.swing.JTextField();
    derecha = new javax.swing.JTextField();
    izquierda = new javax.swing.JTextField();
    abajo = new javax.swing.JTextField();
    disparo = new javax.swing.JTextField();
    cmd = new javax.swing.JTextField();
    chgGun = new javax.swing.JTextField();
    jButton9 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JSeparator();
    defaultsBtn = new javax.swing.JButton();
    exitBtn = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    up = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Options");
    setLocationByPlatform(true);
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(0, 0, 0));
    jPanel1.setForeground(new java.awt.Color(0, 255, 0));

    jLabel8.setBackground(new java.awt.Color(0, 0, 0));
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Cambiar Arma");

    jLabel1.setBackground(new java.awt.Color(0, 0, 0));
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Tecla \"Saltar\"");

    jLabel2.setBackground(new java.awt.Color(0, 0, 0));
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Tecla \"Derecha\"");

    jLabel3.setBackground(new java.awt.Color(0, 0, 0));
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Tecla \"Izquierda\"");

    jLabel4.setBackground(new java.awt.Color(0, 0, 0));
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Tecla \"Agachar\"");

    jLabel5.setBackground(new java.awt.Color(0, 0, 0));
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Boton \"Disparo\"");

    jLabel6.setBackground(new java.awt.Color(0, 0, 0));
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Abrir Consola");

    jLabel7.setBackground(new java.awt.Color(0, 0, 0));
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Tecla de Pausa");

    pausa.setBackground(new java.awt.Color(51, 51, 51));
    pausa.setEditable(false);
    pausa.setForeground(new java.awt.Color(255, 255, 255));
    pausa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        pausaActionPerformed(evt);
      }
    });
    pausa.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        pausaKeyPressed(evt);
      }
    });

    salto.setBackground(new java.awt.Color(51, 51, 51));
    salto.setEditable(false);
    salto.setForeground(new java.awt.Color(255, 255, 255));
    salto.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saltoActionPerformed(evt);
      }
    });
    salto.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        saltoKeyPressed(evt);
      }
    });

    derecha.setBackground(new java.awt.Color(51, 51, 51));
    derecha.setEditable(false);
    derecha.setForeground(new java.awt.Color(255, 255, 255));
    derecha.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        derechaKeyPressed(evt);
      }
    });

    izquierda.setBackground(new java.awt.Color(51, 51, 51));
    izquierda.setEditable(false);
    izquierda.setForeground(new java.awt.Color(255, 255, 255));
    izquierda.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        izquierdaActionPerformed(evt);
      }
    });
    izquierda.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        izquierdaKeyPressed(evt);
      }
    });

    abajo.setBackground(new java.awt.Color(51, 51, 51));
    abajo.setEditable(false);
    abajo.setForeground(new java.awt.Color(255, 255, 255));
    abajo.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        abajoKeyPressed(evt);
      }
    });

    disparo.setBackground(new java.awt.Color(51, 51, 51));
    disparo.setEditable(false);
    disparo.setForeground(new java.awt.Color(255, 255, 255));
    disparo.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        disparoMouseClicked(evt);
      }
    });
    disparo.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        disparoKeyPressed(evt);
      }
    });

    cmd.setBackground(new java.awt.Color(51, 51, 51));
    cmd.setEditable(false);
    cmd.setForeground(new java.awt.Color(255, 255, 255));
    cmd.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        cmdKeyPressed(evt);
      }
    });

    chgGun.setBackground(new java.awt.Color(51, 51, 51));
    chgGun.setEditable(false);
    chgGun.setForeground(new java.awt.Color(255, 255, 255));
    chgGun.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        chgGunKeyPressed(evt);
      }
    });

    jButton9.setBackground(new java.awt.Color(0, 0, 0));
    jButton9.setForeground(new java.awt.Color(0, 255, 0));
    jButton9.setText("Capturar");
    jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton9.setContentAreaFilled(false);
    jButton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton9ActionPerformed(evt);
      }
    });

    jButton8.setBackground(new java.awt.Color(0, 0, 0));
    jButton8.setForeground(new java.awt.Color(0, 255, 0));
    jButton8.setText("Capturar");
    jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton8.setContentAreaFilled(false);
    jButton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton8ActionPerformed(evt);
      }
    });

    jButton7.setBackground(new java.awt.Color(0, 0, 0));
    jButton7.setForeground(new java.awt.Color(0, 255, 0));
    jButton7.setText("Capturar");
    jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton7.setContentAreaFilled(false);
    jButton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton7ActionPerformed(evt);
      }
    });

    jButton6.setBackground(new java.awt.Color(0, 0, 0));
    jButton6.setForeground(new java.awt.Color(0, 255, 0));
    jButton6.setText("Capturar");
    jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton6.setContentAreaFilled(false);
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton6ActionPerformed(evt);
      }
    });

    jButton5.setBackground(new java.awt.Color(0, 0, 0));
    jButton5.setForeground(new java.awt.Color(0, 255, 0));
    jButton5.setText("Capturar");
    jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton5.setContentAreaFilled(false);
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });

    jButton4.setBackground(new java.awt.Color(0, 0, 0));
    jButton4.setForeground(new java.awt.Color(0, 255, 0));
    jButton4.setText("Capturar");
    jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton4.setContentAreaFilled(false);
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jButton3.setBackground(new java.awt.Color(0, 0, 0));
    jButton3.setForeground(new java.awt.Color(0, 255, 0));
    jButton3.setText("Capturar");
    jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton3.setContentAreaFilled(false);
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton2.setBackground(new java.awt.Color(0, 0, 0));
    jButton2.setForeground(new java.awt.Color(0, 255, 0));
    jButton2.setText("Capturar");
    jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton2.setContentAreaFilled(false);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jButton1.setBackground(new java.awt.Color(0, 0, 0));
    jButton1.setForeground(new java.awt.Color(0, 255, 0));
    jButton1.setText("Capturar");
    jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    jButton1.setContentAreaFilled(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    defaultsBtn.setBackground(new java.awt.Color(0, 0, 0));
    defaultsBtn.setForeground(new java.awt.Color(0, 255, 0));
    defaultsBtn.setText("Cargar Defaults");
    defaultsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    defaultsBtn.setContentAreaFilled(false);
    defaultsBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        defaultsBtnActionPerformed(evt);
      }
    });

    exitBtn.setBackground(new java.awt.Color(0, 0, 0));
    exitBtn.setForeground(new java.awt.Color(0, 255, 0));
    exitBtn.setText("Salir");
    exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    exitBtn.setContentAreaFilled(false);
    exitBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitBtnActionPerformed(evt);
      }
    });

    jLabel9.setBackground(new java.awt.Color(0, 0, 0));
    jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel9.setText("Tecla \"Pararse\"");

    up.setBackground(new java.awt.Color(51, 51, 51));
    up.setEditable(false);
    up.setForeground(new java.awt.Color(255, 255, 255));
    up.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        upActionPerformed(evt);
      }
    });
    up.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        upKeyPressed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel9)
          .addComponent(jLabel1)
          .addComponent(jLabel2)
          .addComponent(jLabel3)
          .addComponent(jLabel4)
          .addComponent(jLabel5)
          .addComponent(jLabel6)
          .addComponent(jLabel7)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(pausa, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
              .addComponent(cmd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
              .addComponent(disparo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
              .addComponent(abajo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
              .addComponent(izquierda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
              .addComponent(derecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
              .addComponent(chgGun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButton8)
              .addComponent(jButton7)
              .addComponent(jButton6)
              .addComponent(jButton5)
              .addComponent(jButton4)
              .addComponent(jButton3)
              .addComponent(jButton2)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(salto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(up, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton9)))
        .addGap(241, 241, 241))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(defaultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(39, 39, 39)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jLabel1)
          .addComponent(salto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton9)
          .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton2)
          .addComponent(derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton3)
          .addComponent(izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton4)
          .addComponent(abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton5)
          .addComponent(disparo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton6)
          .addComponent(cmd, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton7)
          .addComponent(pausa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton8)
          .addComponent(chgGun, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addGap(18, 18, 18)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(defaultsBtn)
          .addComponent(exitBtn))
        .addContainerGap(24, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void izquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_izquierdaActionPerformed

private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
// TODO add your handling code here:
   dispose();
   Engine.staticOpt.saveConfig();
   Engine.staticOpt.reset();
}//GEN-LAST:event_exitBtnActionPerformed

private void pausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pausaActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
  listenClicked = true;
  salto.grabFocus();
}//GEN-LAST:event_jButton1ActionPerformed

private void saltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_saltoActionPerformed

private void saltoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saltoKeyPressed
// TODO add your handling code here:
  if(listenClicked && !Engine.staticOpt.contains(evt.getKeyCode())){ 
    Engine.staticOpt.setSalto(evt.getKeyCode());
    salto.setText(getKey(evt));
  }  
}//GEN-LAST:event_saltoKeyPressed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
  listenClicked = true;
  derecha.grabFocus();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    listenClicked = true;
  izquierda.grabFocus();
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    listenClicked = true;
  abajo.grabFocus();
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    listenClicked = true;
  disparo.grabFocus();
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    listenClicked = true;
  cmd.grabFocus();
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
  listenClicked = true;
  pausa.grabFocus();
}//GEN-LAST:event_jButton7ActionPerformed

private void derechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_derechaKeyPressed
// TODO add your handling code here:
  if(listenClicked && !Engine.staticOpt.contains(evt.getKeyCode())){ 
    Engine.staticOpt.setDerecha(evt.getKeyCode());
    derecha.setText(getKey(evt));
  }  
}//GEN-LAST:event_derechaKeyPressed

private void izquierdaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_izquierdaKeyPressed
// TODO add your handling code here:
    if(listenClicked && !Engine.staticOpt.contains(evt.getKeyCode())){ 
    Engine.staticOpt.setIzquierda(evt.getKeyCode());
    izquierda.setText(getKey(evt));
  }  
}//GEN-LAST:event_izquierdaKeyPressed

private void abajoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_abajoKeyPressed
// TODO add your handling code here:
    if(listenClicked && !Engine.staticOpt.contains(evt.getKeyCode())){ 
    Engine.staticOpt.setAbajo(evt.getKeyCode());
    abajo.setText(getKey(evt));
  }  
}//GEN-LAST:event_abajoKeyPressed

private void disparoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disparoKeyPressed
// TODO add your handling code here:
  
}//GEN-LAST:event_disparoKeyPressed

private void cmdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdKeyPressed
// TODO add your handling code here:
   if(listenClicked && !Engine.staticOpt.contains(evt.getKeyCode())){ 
    Engine.staticOpt.setCmd(evt.getKeyCode());
    cmd.setText(getKey(evt));    
  }  
}//GEN-LAST:event_cmdKeyPressed

private void pausaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pausaKeyPressed
// TODO add your handling code here:
  if(listenClicked && !Engine.staticOpt.contains(evt.getKeyCode())){ 
    Engine.staticOpt.setPausa(evt.getKeyCode());
    pausa.setText(getKey(evt));
  }  
}//GEN-LAST:event_pausaKeyPressed

private void disparoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disparoMouseClicked
// TODO add your handling code here:
  if(listenClicked && !Engine.staticOpt.contains(evt.getButton())){ 
    disparo.setText("Boton "+evt.getButton());
    Engine.staticOpt.setDisparo(evt.getButton());
    listenClicked=false;
  }
}//GEN-LAST:event_disparoMouseClicked

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
  listenClicked = true;
  chgGun.grabFocus();  
}//GEN-LAST:event_jButton8ActionPerformed

private void chgGunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chgGunKeyPressed
// TODO add your handling code here:
  if(listenClicked && !Engine.staticOpt.contains(evt.getKeyCode())){ 
    Engine.staticOpt.setGuns(evt.getKeyCode());
    chgGun.setText(getKey(evt));
  }  
}//GEN-LAST:event_chgGunKeyPressed

private void defaultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultsBtnActionPerformed
// TODO add your handling code here:
  Engine.staticOpt.reset();
  Engine.staticOpt.loadDefaults();
  setFields();
  Engine.staticOpt.saveConfig();
}//GEN-LAST:event_defaultsBtnActionPerformed

private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_upActionPerformed

private void upKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upKeyPressed
// TODO add your handling code here:
  if(listenClicked && !Engine.staticOpt.contains(evt.getKeyCode())){ 
    Engine.staticOpt.setUp(evt.getKeyCode());
    up.setText(getKey(evt));
  }  
}//GEN-LAST:event_upKeyPressed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// TODO add your handling code here:
    listenClicked = true;
    up.grabFocus();  
}//GEN-LAST:event_jButton9ActionPerformed

  @SuppressWarnings("static-access")
  public String getKey(java.awt.event.KeyEvent evt){
    String aux=evt.getKeyText(evt.getKeyCode());
    listenClicked=false;
    return aux;
  }

    /**
    * @param args the command line arguments
    */
    

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField abajo;
  private javax.swing.JTextField chgGun;
  private javax.swing.JTextField cmd;
  private javax.swing.JButton defaultsBtn;
  private javax.swing.JTextField derecha;
  private javax.swing.JTextField disparo;
  private javax.swing.JButton exitBtn;
  private javax.swing.JTextField izquierda;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTextField pausa;
  private javax.swing.JTextField salto;
  private javax.swing.JTextField up;
  // End of variables declaration//GEN-END:variables

}
